apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribute-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: tribute
  template:
    metadata:
      labels:
        app: tribute
    spec:
      containers:
        - name: tribute
          image: yash5090/tribute:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
